= https://isaqb.org[iSAQB] Collection of Curricula


This creates the https://isaqb-org.github.io/[main page] that links to the iSAQB curriculae that are maintained in AsciiDoc.

Its online at https://isaqb-org.github.io/

// uncomment, if we have the travis-build enabled!
// image:https://travis-ci.org/isaqb-org/isaqb-org.github.io.svg?branch=master["Build Status", link="https://travis-ci.org/isaqb-org/isaqb-org.github.io"]
image:https://img.shields.io/github/last-commit/isaqb-org/isaqb-org.github.io/master.svg["Last commit"]
image:https://img.shields.io/github/contributors/isaqb-org/isaqb-org.github.io.svg["Contributors",link="https://github.com/isaqb-org/isaqb-org.github.io/graphs/contributors"]
image:https://img.shields.io/github/issues/isaqb-org/isaqb-org.github.io.svg["Issues",link="https://github.com/isaqb-org/isaqb-org.github.io/issues"]

== How-To 

1. Checkout this repository including its submodules (e.g. `git clone --recurse-submodules https://github.com/isaqb-org/isaqb-org.github.io.git`). This automatically includes the `html-theme` submodule which containes the CSS into your clone.
1. The download links for the respective curriculum have to be added to the `docs/index.adoc` file.
1. Run the `gradle` build without parameters, it will generate an `index.html` 
1. The build will copy the generated html to the root of this repository, replacing the existing `index.html`.
1. Test your changes!
1. `git commit -m "<useful message>"` 
1. `git push`

easy, isn't it?


== Questions
Contact one of the https://github.com/isaqb-org/isaqb-org.github.io/graphs/contributors[maintainers] or the iSAQB administrators.

== License
This repo is free to use. 

Please note that the iSAQB curricula (contained in different repositories) are copyrighted!


