= https://isaqb.org[iSAQB] Collection of Curricula


This creates the https://public.isaqb.org/[main page] that links to the iSAQB curriculae that are maintained in AsciiDoc.

Its online at https://public.isaqb.org

image:https://img.shields.io/github/last-commit/isaqb-org/isaqb-org.github.io/main.svg["Last commit"]
image:https://img.shields.io/github/contributors/isaqb-org/isaqb-org.github.io.svg["Contributors",link="https://github.com/isaqb-org/isaqb-org.github.io/graphs/contributors"]
image:https://img.shields.io/github/issues/isaqb-org/isaqb-org.github.io.svg["Issues",link="https://github.com/isaqb-org/isaqb-org.github.io/issues"]

== How-To
. Checkout this repository including its submodules (e.g. `git clone --recurse-submodules https://github.com/isaqb-org/isaqb-org.github.io.git`). This automatically includes the `html-theme` submodule which contains the CSS files for all iSAQB^(R)^ curriculum websites.
. The download links for the respective curriculum have to be added to the `docs/index.adoc` file.
. Run the `gradlew` command without parameters, it will generate an `index.html`.
. The build will copy the generated html file to the root of this repository, replacing the existing `index.html`.
. Test your changes!
. `git commit -m "<useful message>"`
. `git push`

easy, isn't it?

== Questions
Contact one of the https://github.com/isaqb-org/isaqb-org.github.io/graphs/contributors[maintainers] or the iSAQB^(R)^ administrators.

== License
This repo is free to use.

Please note that the iSAQB^(R)^ curricula (contained in different repositories) are under copyright of iSAQB^(R)^!


